const actionTypes = {
  SET_DROPDOWN_OPTIONS: "SET_DROPDOWN_OPTIONS",
  SET_DROPDOWN_VISIBILITY: "SET_DROPDOWN_VISIBILITY",
  SET_DROPDOWN_VALUE: "SET_DROPDOWN_VALUE",
  SET_DROPDOWN_LOADING: "SET_DROPDOWN_LOADING",
  SET_DROPDOWN_SEARCH: "SET_DROPDOWN_SEARCH",
};

export default actionTypes;
